# Generated by Django 5.1.4 on 2025-11-16 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название магазина или компании', max_length=255, verbose_name='Название магазина')),
                ('slug', models.SlugField(help_text='Используется для PostgreSQL схемы: store_{slug}', max_length=100, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, help_text='Описание деятельности магазина', null=True, verbose_name='Описание')),
                ('address', models.TextField(blank=True, help_text='Физический адрес магазина', null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, help_text='Формат: +998XXXXXXXXX', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tenant_key', models.CharField(db_index=True, editable=False, help_text='Уникальный ключ для идентификации магазина в запросах (X-Tenant-Key)', max_length=100, unique=True, verbose_name='Ключ арендатора')),
                ('schema_name', models.CharField(editable=False, help_text='Автоматически генерируется: tenant_{slug}', max_length=63, unique=True, verbose_name='Имя схемы PostgreSQL')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные магазины не могут входить в систему', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(help_text='Пользователь, создавший магазин', on_delete=django.db.models.deletion.PROTECT, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер'), ('cashier', 'Кассир'), ('stockkeeper', 'Складчик')], default='cashier', help_text='Роль сотрудника в магазине', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, help_text='Личный телефон сотрудника', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фото')),
                ('position', models.CharField(blank=True, help_text='Дополнительное описание должности', max_length=100, null=True, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные сотрудники не могут входить в систему', verbose_name='Активен')),
                ('hired_at', models.DateField(auto_now_add=True, verbose_name='Дата найма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='users_store_slug_4e0711_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant_key'], name='users_store_tenant__7270c8_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active'], name='users_store_is_acti_ffda3c_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner'], name='users_store_owner_i_1ac05b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'store'], name='users_emplo_user_id_1fd229_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='users_emplo_role_e06716_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='users_emplo_is_acti_5d4e2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('user', 'store')},
        ),
    ]
