# Generated by Django 5.1.4 on 2025-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Официальное название организации",
                max_length=255,
                null=True,
                verbose_name="Юридическое название",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Область/Регион"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификационный номер налогоплательщика",
                max_length=50,
                null=True,
                verbose_name="ИНН",
            ),
        ),
    ]
