# Generated by Django 5.1.4 on 2025-11-19 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_employee_sex"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Имя сотрудника. Используется если нет user аккаунта",
                max_length=150,
                verbose_name="Имя",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Фамилия сотрудника. Используется если нет user аккаунта",
                max_length=150,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Опционально. Для кассиров без аккаунта можно оставить пустым",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "store"),
                name="unique_user_store",
            ),
        ),
    ]
