# Generated by Django 5.1.4 on 2025-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_cashier_fields_to_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Владелец"),
                    ("manager", "Менеджер"),
                    ("cashier", "Кассир"),
                    ("stockkeeper", "Складчик"),
                    ("staff", "Общий аккаунт сотрудников"),
                ],
                default="cashier",
                help_text="Роль сотрудника в магазине",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
