# Generated by Django 5.1.4 on 2025-11-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        (
            "products",
            "0003_producttag_alter_productbatch_supplier_name_supplier_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_sales_count", models.IntegerField(default=0)),
                (
                    "avg_sale_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cash_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "card_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_items_sold", models.IntegerField(default=0)),
                ("unique_products_sold", models.IntegerField(default=0)),
                ("unique_customers", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                ("sessions_opened", models.IntegerField(default=0)),
                ("sessions_closed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_daily_sales",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="analytics_d_date_d74aab_idx"),
                    models.Index(
                        fields=["date", "total_sales"],
                        name="analytics_d_date_3e0e37_idx",
                    ),
                ],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="CustomerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "recency_days",
                    models.IntegerField(
                        default=0, help_text="Дней с последней покупки"
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(default=0, help_text="Количество покупок"),
                ),
                (
                    "monetary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Общая сумма покупок",
                        max_digits=12,
                    ),
                ),
                (
                    "rfm_score",
                    models.IntegerField(default=0, help_text="RFM score (1-5)"),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True,
                        help_text="Champions, Loyal, At Risk и т.д.",
                        max_length=50,
                    ),
                ),
                ("purchases_count", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("credit_purchases", models.IntegerField(default=0)),
                (
                    "total_credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("avg_payment_delay_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_customer",
                "ordering": ["-monetary"],
                "indexes": [
                    models.Index(
                        fields=["customer"], name="analytics_c_custome_c4a1e3_idx"
                    ),
                    models.Index(
                        fields=["-monetary"], name="analytics_c_monetar_702b09_idx"
                    ),
                    models.Index(
                        fields=["segment"], name="analytics_c_segment_d71b47_idx"
                    ),
                    models.Index(
                        fields=["rfm_score"], name="analytics_c_rfm_sco_0d2784_idx"
                    ),
                ],
                "unique_together": {("customer", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "available_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Количество оборотов",
                        max_digits=5,
                    ),
                ),
                (
                    "days_of_stock",
                    models.IntegerField(
                        default=0, help_text="Дней до исчерпания запасов"
                    ),
                ),
                ("is_out_of_stock", models.BooleanField(default=False)),
                ("is_low_stock", models.BooleanField(default=False)),
                ("is_overstock", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_snapshots",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_inventory_snapshot",
                "ordering": ["-date", "product"],
                "indexes": [
                    models.Index(fields=["-date"], name="analytics_i_date_f64e85_idx"),
                    models.Index(
                        fields=["product", "-date"],
                        name="analytics_i_product_577a94_idx",
                    ),
                    models.Index(
                        fields=["is_low_stock", "-date"],
                        name="analytics_i_is_low__adce72_idx",
                    ),
                    models.Index(
                        fields=["is_out_of_stock", "-date"],
                        name="analytics_i_is_out__697006_idx",
                    ),
                ],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProductPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "quantity_sold",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("sales_count", models.IntegerField(default=0)),
                (
                    "avg_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_product_performance",
                "ordering": ["-date", "-total_revenue"],
                "indexes": [
                    models.Index(
                        fields=["product", "-date"],
                        name="analytics_p_product_27acc1_idx",
                    ),
                    models.Index(
                        fields=["-date", "-total_revenue"],
                        name="analytics_p_date_9e5410_idx",
                    ),
                    models.Index(
                        fields=["-date", "-quantity_sold"],
                        name="analytics_p_date_61f521_idx",
                    ),
                ],
                "unique_together": {("product", "date")},
            },
        ),
    ]
