# Generated by Django 5.1.4 on 2025-11-16 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers_group",
                "ordering": ["-discount_percent", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="customers_g_is_acti_fd77f3_idx"
                    ),
                    models.Index(
                        fields=["discount_percent"],
                        name="customers_g_discoun_c82862_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Физическое лицо"),
                            ("company", "Юридическое лицо"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+998\\d{9}$"
                            )
                        ],
                    ),
                ),
                (
                    "phone_2",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+998\\d{9}$"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "loyalty_points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_purchases_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_purchase_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="customers.customergroup",
                    ),
                ),
            ],
            options={
                "db_table": "customers_customer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Платёж"),
                            ("charge", "Списание"),
                            ("bonus_accrual", "Начисление бонусов"),
                            ("bonus_redemption", "Списание бонусов"),
                            ("correction", "Корректировка"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("performed_by", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="customers.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_transactions",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "customers_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="customers_c_phone_8493fa_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_c_email_4fdeb3_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["group"], name="customers_c_group_i_2291d9_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["is_active", "is_blocked"],
                name="customers_c_is_acti_605a9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="customers_c_last_na_27dbcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company_name"], name="customers_c_company_2610e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_purchase_at"], name="customers_c_last_pu_25011a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(
                fields=["customer", "created_at"], name="customers_t_custome_7e44e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(
                fields=["transaction_type"], name="customers_t_transac_17cb0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(fields=["sale"], name="customers_t_sale_id_4db961_idx"),
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(
                fields=["created_at"], name="customers_t_created_227e2b_idx"
            ),
        ),
    ]
