# Generated by Django 5.1.4 on 2025-11-16 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_producttag_alter_productbatch_supplier_name_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Касса 1, Главная касса', max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код для идентификации', max_length=50, unique=True, verbose_name='Код кассы')),
                ('location', models.CharField(blank=True, help_text='Например: Зал 1, Склад', max_length=200, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, help_text='Касса доступна для работы', verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'db_table': 'sales_cash_register',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_name', models.CharField(help_text='Временно строка, позже будет FK → User', max_length=200, verbose_name='Кассир')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта'), ('suspended', 'Приостановлена')], default='open', max_length=20, verbose_name='Статус')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, help_text='Сколько денег было в кассе при открытии смены', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Начальная сумма наличных')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='Сколько должно быть денег по расчётам', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ожидаемая сумма наличных')),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Сколько денег фактически в кассе при закрытии', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фактическая сумма наличных')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, help_text='Фактическая - Ожидаемая (+ излишек, - недостача)', max_digits=12, verbose_name='Разница')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sales.cashregister', verbose_name='Касса')),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'db_table': 'sales_cashier_session',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Уникальный номер чека', max_length=50, unique=True, verbose_name='Номер чека')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('customer_name', models.CharField(blank=True, help_text='Временно строка, позже будет FK → Customer', max_length=200, verbose_name='Клиент')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон клиента')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма без скидки')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент скидки')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма налога')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговая сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.cashiersession', verbose_name='Кассовая смена')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sales_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Перевод'), ('online', 'Онлайн оплата'), ('credit', 'В кредит'), ('other', 'Другое')], max_length=20, verbose_name='Способ оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Для наличных - сколько дал клиент', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Получено')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сдача')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры карты')),
                ('transaction_id', models.CharField(blank=True, help_text='Номер транзакции для безналичных', max_length=100, verbose_name='ID транзакции')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.cashiersession', verbose_name='Кассовая смена')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'sales_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Цена на момент продажи', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка на позицию')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка НДС (%)')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='quantity * unit_price - discount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма позиции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('batch', models.ForeignKey(blank=True, help_text='Партия товара для списания (FEFO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.productbatch', verbose_name='Партия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Товар')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.stockreservation', verbose_name='Резервирование')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Позиция продажи',
                'verbose_name_plural': 'Позиции продаж',
                'db_table': 'sales_sale_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('cash_in', 'Внесение'), ('cash_out', 'Изъятие')], max_length=20, verbose_name='Тип операции')),
                ('reason', models.CharField(choices=[('collection', 'Инкассация'), ('change', 'Размен'), ('float', 'Пополнение сдачи'), ('expense', 'Расход'), ('correction', 'Корректировка'), ('other', 'Другое')], max_length=20, verbose_name='Причина')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('performed_by', models.CharField(help_text='Временно строка, позже будет FK → User', max_length=200, verbose_name='Выполнил')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='sales.cashiersession', verbose_name='Кассовая смена')),
            ],
            options={
                'verbose_name': 'Движение наличности',
                'verbose_name_plural': 'Движения наличности',
                'db_table': 'sales_cash_movement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'movement_type'], name='sales_cash__session_3fdfcd_idx'), models.Index(fields=['created_at'], name='sales_cash__created_1c0326_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['cash_register', 'status'], name='sales_cashi_cash_re_bf7baa_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['status', 'opened_at'], name='sales_cashi_status_dc81a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['session', 'status'], name='sales_sale_session_51c51f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['receipt_number'], name='sales_sale_receipt_f5ff95_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'created_at'], name='sales_sale_status_23c89c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale'], name='sales_payme_sale_id_b07c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['session', 'payment_method'], name='sales_payme_session_5321fa_idx'),
        ),
    ]
