# Generated by Django 5.1.4 on 2025-11-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_producttag_alter_productbatch_supplier_name_supplier_and_more",
        ),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cashregister",
            index=models.Index(fields=["code"], name="sales_cash__code_934214_idx"),
        ),
        migrations.AddIndex(
            model_name="cashregister",
            index=models.Index(
                fields=["is_active"], name="sales_cash__is_acti_00da19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["sale", "product"], name="sales_sale__sale_id_3296d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(fields=["batch"], name="sales_sale__batch_i_a6f596_idx"),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["product"], name="sales_sale__product_d279c6_idx"
            ),
        ),
    ]
