# Generated by Django 5.1.4 on 2025-11-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_cashregister_sales_cash__code_934214_idx_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashmovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_movements",
                to="users.employee",
                verbose_name="Выполнил",
            ),
        ),
    ]
