# Generated by Django 5.1.4 on 2025-11-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customertransaction_performed_by"),
        ("sales", "0003_alter_cashmovement_performed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Покупатель (опционально)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Используется если customer не указан",
                max_length=200,
                verbose_name="Имя клиента",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="Используется если customer не указан",
                max_length=20,
                verbose_name="Телефон клиента",
            ),
        ),
    ]
