# Generated by Django 5.1.4 on 2025-11-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_add_customer_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_last4",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Последние 4 цифры карты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Номер транзакции для безналичных",
                max_length=100,
                null=True,
                verbose_name="ID транзакции",
            ),
        ),
    ]
