# Generated by Django 5.1.4 on 2025-11-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_fix_payment_nullable_fields"),
        ("users", "0004_add_cashier_fields_to_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashiersession",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                help_text="Сотрудник, работающий на этой смене",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashier_sessions",
                to="users.employee",
                verbose_name="Кассир",
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="cashier_name",
            field=models.CharField(
                blank=True,
                help_text="Используется только для старых записей. Новые смены используют cashier (FK)",
                max_length=200,
                null=True,
                verbose_name="Имя кассира (устарело)",
            ),
        ),
    ]
