# Generated by Django 5.1.4 on 2025-11-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_sale_cashier"),
        ("users", "0005_add_staff_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Кассир, который совершил продажу",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="users.employee",
                verbose_name="Кассир",
            ),
        ),
    ]
