# Generated by Django 5.1.4 on 2025-11-16 08:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Цвет, Размер, Материал', max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('select', 'Выбор из списка'), ('multiselect', 'Множественный выбор'), ('boolean', 'Да/Нет')], default='text', max_length=20, verbose_name='Тип атрибута')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=False, help_text='Обязателен ли этот атрибут для товаров', verbose_name='Обязательный')),
                ('is_filterable', models.BooleanField(default=True, help_text='Использовать в фильтрах товаров', verbose_name='Для фильтрации')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'db_table': 'products_attribute',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: шт, кг, л, м', max_length=50, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(help_text='Например: шт, кг', max_length=10, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'db_table': 'products_unit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Например: Красный, L, Хлопок', max_length=200, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'db_table': 'products_attribute_value',
                'ordering': ['attribute', 'order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL-friendly идентификатор', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'products_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара', max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sku', models.CharField(help_text='Уникальный артикул товара (SKU)', max_length=100, unique=True, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Штрихкод для сканера', max_length=100, verbose_name='Штрихкод')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное изображение')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объём (л)')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен для продажи', verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать в рекомендованных', verbose_name='Рекомендуемый')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, verbose_name='Текстовое значение')),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Числовое значение')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='Товар')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.attributevalue', verbose_name='Выбранное значение')),
            ],
            options={
                'verbose_name': 'Атрибут товара',
                'verbose_name_plural': 'Атрибуты товаров',
                'db_table': 'products_product_attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'products_product_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Уведомление при достижении минимума', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный остаток')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Максимальное количество на складе', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальный остаток')),
                ('track_inventory', models.BooleanField(default=True, help_text='Вести учёт количества товара', verbose_name='Учёт остатков')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остатки товара',
                'verbose_name_plural': 'Остатки товаров',
                'db_table': 'products_product_inventory',
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Цена закупки', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Розничная цена', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продажи')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена для оптовых покупателей', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оптовая цена')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Например: 12, 15, 20', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка НДС (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цены товара',
                'verbose_name_plural': 'Цены товаров',
                'db_table': 'products_product_pricing',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['quantity'], name='products_pr_quantit_332337_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['track_inventory'], name='products_pr_track_i_c5fde9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
    ]
