# Generated by Django 5.1.4 on 2025-11-16 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Номер партии или накладной', max_length=100, verbose_name='Номер партии')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в партии')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Цена закупки этой партии', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена закупки')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Дата производства')),
                ('expiry_date', models.DateField(blank=True, help_text='Дата окончания срока годности', null=True, verbose_name='Срок годности')),
                ('supplier_name', models.CharField(blank=True, help_text='Название поставщика (временно)', max_length=200, verbose_name='Поставщик')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, help_text='Партия доступна для продажи', verbose_name='Активна')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Партия товара',
                'verbose_name_plural': 'Партии товаров',
                'db_table': 'products_product_batch',
                'ordering': ['expiry_date', 'received_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name': 'Настройки учёта товара', 'verbose_name_plural': 'Настройки учёта товаров'},
        ),
        migrations.RemoveIndex(
            model_name='productinventory',
            name='products_pr_quantit_332337_idx',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_eabc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['expiry_date'], name='products_pr_expiry__13d871_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['received_at'], name='products_pr_receive_62de22_idx'),
        ),
    ]
