# Generated by Django 5.1.4 on 2025-11-16 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productbatch_alter_productinventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Новинка, Хит продаж', max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex цвет для отображения: #RRGGBB', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, help_text='Название иконки (например, из Font Awesome)', max_length=50, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тег товара',
                'verbose_name_plural': 'Теги товаров',
                'db_table': 'products_product_tag',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Название поставщика (для обратной совместимости)', max_length=200, verbose_name='Поставщик (строка)'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название поставщика', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код для идентификации', max_length=50, null=True, unique=True, verbose_name='Код поставщика')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('payment_terms', models.CharField(blank=True, help_text='Например: предоплата, отсрочка 30 дней', max_length=200, verbose_name='Условия оплаты')),
                ('delivery_time', models.IntegerField(blank=True, help_text='Среднее время доставки в днях', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Срок поставки (дней)')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа')),
                ('rating', models.IntegerField(default=0, help_text='От 0 до 5 звезд', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, help_text='Работаем ли с этим поставщиком', verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'products_supplier',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='products_su_is_acti_0ef23a_idx'), models.Index(fields=['rating'], name='products_su_rating_f74d90_idx')],
            },
        ),
        migrations.AddField(
            model_name='productbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='products.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Уникальный штрих-код', max_length=100, unique=True, verbose_name='Штрих-код')),
                ('barcode_type', models.CharField(choices=[('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upc', 'UPC'), ('qr', 'QR Code'), ('code128', 'Code 128'), ('code39', 'Code 39'), ('internal', 'Внутренний код')], default='ean13', max_length=20, verbose_name='Тип штрих-кода')),
                ('is_primary', models.BooleanField(default=False, help_text='Основной штрих-код для печати', verbose_name='Основной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Штрих-код товара',
                'verbose_name_plural': 'Штрих-коды товаров',
                'db_table': 'products_product_barcode',
                'ordering': ['-is_primary', 'barcode'],
                'indexes': [models.Index(fields=['barcode'], name='products_pr_barcode_f5ee1e_idx'), models.Index(fields=['product', 'is_primary'], name='products_pr_product_ffb5bc_idx')],
                'unique_together': {('product', 'barcode')},
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('order_id', models.IntegerField(blank=True, help_text='Временно используем ID, позже будет FK', null=True, verbose_name='ID заказа')),
                ('order_reference', models.CharField(blank=True, help_text='Номер заказа для отображения', max_length=100, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Выполнено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='active', max_length=20, verbose_name='Статус')),
                ('reserved_until', models.DateTimeField(blank=True, help_text='Автоматически освободится после этой даты', null=True, verbose_name='Зарезервировано до')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата резервирования')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.CharField(blank=True, help_text='Временно строка, позже будет FK → User', max_length=100, verbose_name='Создал')),
                ('batch', models.ForeignKey(blank=True, help_text='Конкретная партия для резервирования (FEFO)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.productbatch', verbose_name='Партия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Резервирование товара',
                'verbose_name_plural': 'Резервирование товаров',
                'db_table': 'products_stock_reservation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='products_st_product_5d918a_idx'), models.Index(fields=['batch', 'status'], name='products_st_batch_i_587892_idx'), models.Index(fields=['order_id'], name='products_st_order_i_924f55_idx'), models.Index(fields=['reserved_until'], name='products_st_reserve_5fda24_idx'), models.Index(fields=['status', 'created_at'], name='products_st_status_01e105_idx')],
            },
        ),
    ]
