# Generated by Django 5.1.4 on 2025-11-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_producttag_alter_productbatch_supplier_name_supplier_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockreservation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_reservations",
                to="users.employee",
                verbose_name="Создал",
            ),
        ),
    ]
