# Generated by Django 5.1.4 on 2025-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_stockreservation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="productbatch",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Автоматически генерируется для каждой партии",
                max_length=100,
                verbose_name="Штрихкод партии",
            ),
        ),
    ]
