# Generated by Django 5.1.4 on 2025-11-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productbatch_barcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Обязателен ли этот атрибут для товаров данной категории",
                        verbose_name="Обязательный",
                    ),
                ),
                (
                    "is_variant",
                    models.BooleanField(
                        default=False,
                        help_text="Создавать варианты товара на основе этого атрибута (например, разные цвета)",
                        verbose_name="Используется для вариантов",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="products.attribute",
                        verbose_name="Атрибут",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="products.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут категории",
                "verbose_name_plural": "Атрибуты категорий",
                "db_table": "products_category_attribute",
                "ordering": ["category", "order", "attribute__name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="products_ca_categor_f69c63_idx"
                    ),
                    models.Index(
                        fields=["attribute"], name="products_ca_attribu_13ce4f_idx"
                    ),
                ],
                "unique_together": {("category", "attribute")},
            },
        ),
    ]
